version: '3.1'

services:

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 27017:27017