version: '3.1'

services:

#  web:
#    container_name: dockerdev
#    build: ./
#    ports:
#      - "8000:8080"
#    environment:
#      DD_DB_HOST: db
#    command: /server
#    depends_on:
#      - db

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123